name: mountain
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # fluent_ui: ^4.11.2
  # fluentui_system_icons: ^1.1.273
  flutter_i18n: ^0.36.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  file_picker: ^8.3.1
  path_provider: ^2.1.5
  path: ^1.9.0
  window_manager: ^0.4.3
  go_router: ^14.8.0
  # drift: ^2.25.1
  system_theme: ^3.1.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.2
  shared_preferences_riverpod: ^0.3.0
  card_settings_ui: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # json_serializable: ^6.9.3
  build_runner: ^2.4.14

build_runner:
  targets:
    - name: mountain
      module: package:mountain/main.dart
      output: lib/main.g.dart

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
